apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dark

resources:
  - https://github.com/K-Phoen/dark/config/crd
  - https://github.com/K-Phoen/dark/config/rbac
  - https://github.com/K-Phoen/dark/config/operator

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: dark
      namespace: dark
    spec:
      template:
        spec:
          containers:
            - name: dark
              env:
                - name: GRAFANA_TOKEN
                  $patch: delete
