---
extends: default

rules:
  line-length:
    ignore: |
      resources/
      policies/
  indentation:
    ignore: |
      resources/
      policies/
  new-line-at-end-of-file:
    ignore: |
      policies/
