apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dark
  name: dark
  namespace: dark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dark
      app.kubernetes.io/name: dark
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: dark
        app.kubernetes.io/name: dark
    spec:
      containers:
      - args:
        - --zap-devel=false
        command:
        - /operator
        env:
        - name: GRAFANA_HOST
          value: http://grafana.monitoring.svc.cluster.local
        image: kphoen/dark:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: dark
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 50m
            memory: 80Mi
          requests:
            cpu: 5m
            memory: 30Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
      securityContext:
        runAsNonRoot: true
      serviceAccountName: dark-operator
      terminationGracePeriodSeconds: 10
