---
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Nix Store
        id: cache-nix-store
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Run kyverno tests
        run: nix develop --command make test
      - run: ls /nix && ls /nix/store
