---
name: push-sign-artifact

on:
  push:
    branches:
      - 'main'

permissions:
  packages: write    # needed for ghcr.io access
  id-token: write    # needed for keyless signing

env:
  oci_repo: "oci://ghcr.io/tguimbert/manifests/dark"

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Setup Cosign
        uses: sigstore/cosign-installer@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push and sign manifests
        id: push
        run: |
          echo digest="$(flux push artifact \
          ${{ env.oci_repo }}:${{ github.ref_name }} \
          --path='./resources/dark/' \
          --source=${{ github.repositoryUrl }} \
          --revision='${{ github.ref_name }}@sha1:${{ github.sha }}' \
          --output json | \
          jq -r '. | .digest')" >> "$GITHUB_OUTPUT"
      - name: Sign manifests in GHCR with Cosign
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign ${{ env.oci_repo}}@${{ steps.push.outputs.digest }}
